packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Better Auth
  "@better-auth/expo": "^1.3.26"
  "better-auth": "^1.3.26"
  "@better-auth/cli": "^1.3.26"

  # Dev tooling
  eslint: ^9.21.0
  prettier: ^3.7.4
  tailwindcss: ^3.4.15
  typescript: ^5.8.3
  turbo: ^2.6.3
  "@turbo/gen": ^2.6.3

  # Misc
  zod: ^3.25.49
  "@t3-oss/env-nextjs": ^0.13.6
  superjson: ^2.2.6
  "@types/node": ^22.15.0

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.7.2
  "@trpc/tanstack-react-query": ^11.7.2
  "@trpc/server": ^11.7.2

  # Next.js
  next: ^15.4.8

  # AI SDK
  "ai": ^5.0.52
  "@ai-sdk/google": ^2.0.3

catalogs:
  react19:
    react: ^19.2.1
    react-dom: ^19.2.1
    "@types/react": ~19.2.1
    "@types/react-dom": ^19.2.1
