packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Better Auth
  "@better-auth/expo": 1.4.0-beta.9
  "@better-auth/cli": 1.4.0-beta.9
  "better-auth": 1.4.0-beta.9

  # Dev tooling
  "@eslint/js": ^9.38.0
  eslint: ^9.38.0
  prettier: ^3.7.4
  tailwindcss: ^4.1.16
  "@tailwindcss/postcss": ^4.1.16
  typescript: ^5.9.3

  # Misc
  zod: ^4.1.12
  "@t3-oss/env-nextjs": ^0.13.8
  superjson: ^2.2.6
  "@types/node": ^22.18.12

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.90.12
  "@trpc/client": ^11.7.2
  "@trpc/tanstack-react-query": ^11.7.2
  "@trpc/server": ^11.7.2

  # Next.js
  next: ^16.0.7

  # AI SDK
  "ai": ^5.0.52
  "@ai-sdk/google": ^2.0.3

  turbo: ^2.6.3
  "@turbo/gen": ^2.6.3

catalogs:
  react19:
    "@types/react": ~19.1.0
    "@types/react-dom": ~19.1.0
    react: 19.1.2
    react-dom: 19.1.2

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
