packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@ai-sdk/react": ^3.0.118
  autumn-js: ^1.0.7
  "@eslint/js": ^9.39.4
  "@t3-oss/env-nextjs": ^0.13.10
  "@tailwindcss/postcss": ^4.2.2
  "@tanstack/react-query": ^5.91.3
  "@trpc/client": ^11.14.1
  "@trpc/server": ^11.14.1
  "@trpc/tanstack-react-query": ^11.14.1
  "@turbo/gen": ^2.8.20
  "@types/node": ^22.19.15
  ai: ^6.0.116
  babel-plugin-react-compiler: ^1.0.0
  eslint: ^9.39.4
  next: ^16.2.0
  prettier: ^3.8.1
  superjson: ^2.2.6
  tailwindcss: ^4.2.2
  turbo: ^2.8.20
  typescript: ^5.9.3
  zod: ^4.3.6

catalogs:
  better-auth:
    "@better-auth/expo": 1.5.5
    better-auth: 1.5.5
  react19:
    "@types/react": ~19.2.14
    "@types/react-dom": ~19.2.3
    react: 19.2.4
    react-dom: 19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
