packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  # Better Auth
  "@better-auth/expo": "^1.3.4"
  "better-auth": "^1.3.4"

  # Dev tooling
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.15
  typescript: ^5.9.0
  turbo: ^2.5.5
  "@turbo/gen": ^2.5.5

  # Misc
  zod: ^3.25.49
  "@t3-oss/env-nextjs": ^0.13.6

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.4.3
  "@trpc/tanstack-react-query": ^11.4.3
  "@trpc/server": ^11.4.3

  # Next.js
  next: ^15.4.5

  # AI SDK
  "ai": ^5.0.8
  "@ai-sdk/google": ^2.0.3

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ~19.0.10
    "@types/react-dom": ^19.0.0
